# Generated by Django 2.1.7 on 2019-03-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_blog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
    ]
